### ISSUE TITLE
Missing libswift when linking swift frameworks

### ISSUE THREAD

**Issue by mevinDhun** [theos/theos#418]
Hi,
I have a 3rd party framework `CoreMLHelpers` which contains swift code and I can use it in my ios objective-c app. When i link it for my tweak, the tweak does not run (no log appear). Here is my makefile:
```
BUNDLE_NAME = com.karim.fritzer
com.karim.fritzer_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries
TWEAK_NAME = fritzer
fritzer_FILES = Tweak.xm
fritzer_FRAMEWORKS = CoreML ImageIO Accelerate AVFoundation CoreMLHelpers
include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/bundle.mk
include $(THEOS_MAKE_PATH)/tweak.mk
fritzer_LDFLAGS += -F./
after-install::
    install.exec "killall -9 Camera"
```
Tweak.xm:
```
%ctor {
 NSLog(@"[karim] init fritzer tweak");
 void *handle = dlopen([@"/Library/MobileSubstrate/DynamicLibraries/com.karim.fritzer.bundle/CoreMLHelpers.framework/CoreMLHelpers" UTF8String], RTLD_NOW);
 if (handle == NULL) {
    char *error = dlerror();
     NSLog(@"dlopen error: %s", error);
  }
}
```

If i remove the `CoreMLHelpers` from frameworks in my makefile, the tweak loads but it fails to open it:
```
Library not loaded: @rpath/libswiftAccelerate.dylib
Referenced from: /Library/MobileSubstrate/DynamicLibraries/com.karim.fritzer.bundle/CoreMLHelpers.framework/CoreMLHelpers
Reason: image not found
```
This `libswiftAccelerate.dylib` is missing usually get bundled in apps by xcode. My question is how do i tell theos to bundle the system swift libs which are automatically embedded when using an xcode app?
I know theos can compile swift files but does it support embedding swift frameworks?

**Comment by kabiroberai** [comment]
The second issue should be resolved by #417. Please switch to that branch and let me know if it works.

**Comment by mevinDhun** [comment]
@kabiroberai I saw it was merged into master, so i updated to latest master version but the issue is still present. Not sure if i was clear enough but I am using a normal objective c tweak but with frameworks that use swift codes.

> xcrun swift -version

`Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)`

Here is a verbose log when i compile the tweak:
```
MacBook-Air:fritzer karim$ make package install messages=yes
> Making all for bundle com.karim.fritzer…
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/com.karim.fritzer.bundle")
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/com.karim.fritzer.bundle")
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/com.karim.fritzer.bundle")
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 5 "Copying resource directories into the bundle wrapper"); set -o pipefail; (for d in Resources; do \
                if [[ -d "$d" ]]; then \
                        rsync -a "$d/" "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/com.karim.fritzer.bundle/" --exclude "_MTN" --exclude ".git" --exclude ".svn" --exclude ".DS_Store" --exclude "._*"; \
                else \
                        printf "\e[0;33m==> \e[1;33mWarning:\e[m %s\n" "Ignoring missing bundle resource directory $d." >&2; \
                fi; \
        done)
==> Copying resource directories into the bundle wrapper…
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-keep-going COLOR=1 \
                internal-bundle-compile \
                _THEOS_CURRENT_TYPE=bundle THEOS_CURRENT_INSTANCE=com.karim.fritzer _THEOS_CURRENT_OPERATION=compile \
                THEOS_BUILD_DIR="." _THEOS_MAKE_PARALLEL=yes
==> Warning: No files to link - creating a bundle containing only resources
> Making all for tweak fritzer…
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-keep-going COLOR=1 \
                internal-library-compile \
                _THEOS_CURRENT_TYPE=tweak THEOS_CURRENT_INSTANCE=fritzer _THEOS_CURRENT_OPERATION=compile \
                THEOS_BUILD_DIR="." _THEOS_MAKE_PARALLEL=yes
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-print-directory --no-keep-going internal-tweak-compile _THEOS_CURRENT_TYPE="tweak" THEOS_CURRENT_INSTANCE="fritzer" _THEOS_CURRENT_OPERATION="compile" THEOS_BUILD_DIR="." THEOS_CURRENT_ARCH="arm64"
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 1 "Preprocessing Tweak.xm"); set -o pipefail; (/Users/karim/theos/bin/logos.pl -c warnings=error -c generator=MobileSubstrate    Tweak.xm > /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/Tweak.xm.mm)
==> Preprocessing Tweak.xm…
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 2 "Compiling Tweak.xm (arm64)"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -x objective-c++ -c -I"/Users/karim/Documents/workspace/fritzer" -I/Users/karim/theos/include -I/Users/karim/theos/vendor/include -I/Users/karim/theos/include/_fallback -include /Users/karim/theos/Prefix.pch -MT /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/Tweak.xm.32a44d18.o -MMD -MP -MF "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/Tweak.xm.32a44d18.Td" -fcolor-diagnostics -DTARGET_IPHONE=1 -O0 -Wall -ggdb -Werror  -isysroot "/Users/karim/theos/sdks/iPhoneOS11.2.sdk" -miphoneos-version-min=11.2 -fmodules -fcxx-modules -fmodule-name=fritzer -fbuild-session-file=/Users/karim/Documents/workspace/fritzer/.theos/build_session -fmodules-prune-after=345600 -fmodules-prune-interval=86400 -fmodules-validate-once-per-build-session    -DDEBUG -O0  -DTHEOS_INSTANCE_NAME="\"fritzer\"" -fmodules -fcxx-modules -fmodule-name=fritzer -fbuild-session-file=/Users/karim/Documents/workspace/fritzer/.theos/build_session -fmodules-prune-after=345600 -fmodules-prune-interval=86400 -fmodules-validate-once-per-build-session  -arch arm64               /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/Tweak.xm.mm -o /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/Tweak.xm.32a44d18.o)
==> Compiling Tweak.xm (arm64)…
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 3 "Linking tweak fritzer (arm64)"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fcolor-diagnostics -L/Users/karim/theos/lib -ggdb -L/Users/karim/theos/vendor/lib -lobjc -framework Foundation -framework CoreFoundation -ObjC++ -fobjc-exceptions -fobjc-call-cxx-cdtors  -framework CoreML -framework ImageIO -framework Accelerate -framework AVFoundation            -F/Users/karim/theos/vendor/lib -framework CydiaSubstrate -dynamiclib -install_name "/Library/MobileSubstrate/DynamicLibraries/fritzer.dylib"  -isysroot "/Users/karim/theos/sdks/iPhoneOS11.2.sdk" -miphoneos-version-min=11.2  -multiply_defined suppress  -arch arm64 -F./ -O0 -o "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/fritzer.dylib" /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/Tweak.xm.32a44d18.o)
==> Linking tweak fritzer (arm64)…
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 4 "Generating debug symbols for fritzer"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-dsymutil "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/fritzer.dylib")
==> Generating debug symbols for fritzer…
rm /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/Tweak.xm.mm
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 4 "Merging tweak fritzer"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -arch arm64 /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/arm64/fritzer.dylib -create -output "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/fritzer.dylib.47ba6b93.unsigned")
==> Merging tweak fritzer…
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 4 "Signing fritzer"); set -o pipefail; (CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate  ldid -S "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/fritzer.dylib.47ba6b93.unsigned" && mv "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/fritzer.dylib.47ba6b93.unsigned" "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/fritzer.dylib")
==> Signing fritzer…
set -o pipefail; (rm -rf "/Users/karim/Documents/workspace/fritzer/.theos/_")
set -o pipefail; (/Users/karim/theos/bin/fakeroot.sh -p "/Users/karim/Documents/workspace/fritzer/.theos/fakeroot" -c)
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/fritzer/.theos/_")
set -o pipefail; ([ -d layout ] && rsync -a "layout/" "/Users/karim/Documents/workspace/fritzer/.theos/_" --exclude "DEBIAN" --exclude "_MTN" --exclude ".git" --exclude ".svn" --exclude ".DS_Store" --exclude "._*" || true)
> Making stage for bundle com.karim.fritzer…
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/fritzer/.theos/_/Library/MobileSubstrate/DynamicLibraries/com.karim.fritzer.bundle")
set -o pipefail; (rsync -a "/Users/karim/Documents/workspace/fritzer/.theos/obj/debug/com.karim.fritzer.bundle/" "/Users/karim/Documents/workspace/fritzer/.theos/_/Library/MobileSubstrate/DynamicLibraries/com.karim.fritzer.bundle")
> Making stage for tweak fritzer…
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/fritzer/.theos/_/Library/MobileSubstrate/DynamicLibraries/")
set -o pipefail; (cp /Users/karim/Documents/workspace/fritzer/.theos/obj/debug/fritzer.dylib "/Users/karim/Documents/workspace/fritzer/.theos/_/Library/MobileSubstrate/DynamicLibraries/")
set -o pipefail; (cp fritzer.plist "/Users/karim/Documents/workspace/fritzer/.theos/_/Library/MobileSubstrate/DynamicLibraries/")
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/fritzer/.theos/_/DEBIAN")
set -o pipefail; (sed -e 's/\${LIBSWIFT}/com.modmyi.libswift4 (>= 4.2.1)/g; s/\${LIBSWIFT_VERSION}/4.2.1/g; /^[Vv]ersion:/d; /^$/d; $a\' "/Users/karim/Documents/workspace/fritzer/control" > "/Users/karim/Documents/workspace/fritzer/.theos/_/DEBIAN/control")
set -o pipefail; (echo "Version: 0.0.1-18+debug" >> "/Users/karim/Documents/workspace/fritzer/.theos/_/DEBIAN/control")
set -o pipefail; (echo "Installed-Size: 37444" >> "/Users/karim/Documents/workspace/fritzer/.theos/_/DEBIAN/control")
set -o pipefail; (COPYFILE_DISABLE=1 /Users/karim/theos/bin/fakeroot.sh -p "/Users/karim/Documents/workspace/fritzer/.theos/fakeroot" -r dm.pl -Zlzma -z0 -b "/Users/karim/Documents/workspace/fritzer/.theos/_" "./packages/com.karim.fritzer_0.0.1-18+debug_iphoneos-arm.deb")
dm.pl: building package `com.karim.fritzer:iphoneos-arm' in `./packages/com.karim.fritzer_0.0.1-18+debug_iphoneos-arm.deb'

```

**Comment by mevinDhun** [comment]
I managed to get the swift libs to load inside the app. I created a symlink to where libswift gets installed:
```
ln -s /usr/lib/libswift/4.2.1 /Applications/Camera.app/Frameworks
```

**Comment by kabiroberai** [comment]
You shouldn’t be doing that. Instead, create an empty swift file inside your tweak and add it to your `FILES` to signal that you’re using Swift. Also add `${LIBSWIFT}` to your dependencies (Theos automatically substitutes it with the correct libswift version).

One more thing: It isn’t a good idea to use Swift 4.2 in tweaks since it isn’t ABI stable. I’d recommend switching to 5.0 or higher if that’s possible.

**Comment by mevinDhun** [comment]
I already have tried some swift category files in the project and they compile and work fine (Not sure how). 
```
testtweak_FILES = Tweak.xm MLMultiArray+Helpers.swift
```

Concerning my control file, i have this line:
`Depends: mobilesubstrate, preferenceloader, com.modmyi.libswift4`
I'll switch it to the one you recommended.

And regarding swift 5, i cannot switch since the frameworks i am using are not compatible with it yet. And my tweak is only going to be injected inside camera app which is a non-swift app, so the ABI should not cause any problem i guess.

**Comment by mevinDhun** [comment]
Update:
I upgraded to swift 5, remove everything and created a new tweak with latest theos. Added a swift file in it and linked against Accelerate framework. When attempting to load the 3rd party framework, it still fails with same error:
```
 Error loading /Library/MobileSubstrate/DynamicLibraries/com.karim.swifter.bundle/Frameworks/CoreMLHelpers.framework/CoreMLHelpers:  dlopen(/Library/MobileSubstrate/DynamicLibraries/com.karim.swifter.bundle/Frameworks/CoreMLHelpers.framework/CoreMLHelpers, 265): Library not loaded: @rpath/libswiftAccelerate.dylib
  Referenced from: /Library/MobileSubstrate/DynamicLibraries/com.karim.swifter.bundle/Frameworks/CoreMLHelpers.framework/CoreMLHelpers
  Reason: image not found
```

**Comment by kabiroberai** [comment]
What’s the output of `otool -l .theos/_/Library/MobileSubstrate/DynamicLibraries/com.karim.swifter.bundle/Frameworks/CoreMLHelpers.framework/CoreMLHelpers`?

**Comment by mevinDhun** [comment]
```
otool -l .theos/_/Library/MobileSubstrate/DynamicLibraries/com.karim.swifter.bundle/Frameworks/CoreMLHelpers.framework/CoreMLHelpers
.theos/_/Library/MobileSubstrate/DynamicLibraries/com.karim.swifter.bundle/Frameworks/CoreMLHelpers.framework/CoreMLHelpers:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    45       4592 0x02100085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 1352
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x0000000000011000
  fileoff 0
 filesize 69632
  maxprot 0x00000007
 initprot 0x00000005
   nsects 16
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000001470
      size 0x000000000000e7c2
    offset 5232
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x000000000000fc32
      size 0x00000000000002dc
    offset 64562
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x000000000000ff10
      size 0x00000000000004d4
    offset 65296
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x00000000000103f0
      size 0x00000000000003d8
    offset 66544
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_methname
   segname __TEXT
      addr 0x00000000000107c8
      size 0x000000000000015d
    offset 67528
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __swift5_typeref
   segname __TEXT
      addr 0x0000000000010926
      size 0x00000000000000cb
    offset 67878
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_proto
   segname __TEXT
      addr 0x00000000000109f4
      size 0x000000000000001c
    offset 68084
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_types
   segname __TEXT
      addr 0x0000000000010a10
      size 0x000000000000001c
    offset 68112
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_capture
   segname __TEXT
      addr 0x0000000000010a2c
      size 0x0000000000000044
    offset 68140
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x0000000000010a70
      size 0x0000000000000229
    offset 68208
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __swift5_builtin
   segname __TEXT
      addr 0x0000000000010c9c
      size 0x0000000000000028
    offset 68764
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_fieldmd
   segname __TEXT
      addr 0x0000000000010cc4
      size 0x0000000000000050
    offset 68804
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_reflstr
   segname __TEXT
      addr 0x0000000000010d14
      size 0x000000000000001c
    offset 68884
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __swift5_protos
   segname __TEXT
      addr 0x0000000000010d30
      size 0x0000000000000004
    offset 68912
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x0000000000010d34
      size 0x000000000000025c
    offset 68916
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x0000000000010f90
      size 0x0000000000000070
    offset 69520
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 792
  segname __DATA
   vmaddr 0x0000000000011000
   vmsize 0x0000000000001000
  fileoff 69632
 filesize 4096
  maxprot 0x00000007
 initprot 0x00000003
   nsects 9
    flags 0x0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x0000000000011000
      size 0x0000000000000010
    offset 69632
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 122 (index into indirect symbol table)
 reserved2 0
Section
  sectname __got
   segname __DATA
      addr 0x0000000000011010
      size 0x0000000000000138
    offset 69648
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 124 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x0000000000011148
      size 0x00000000000003d0
    offset 69960
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 163 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x0000000000011518
      size 0x0000000000000288
    offset 70936
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_imageinfo
   segname __DATA
      addr 0x00000000000117a0
      size 0x0000000000000008
    offset 71584
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __objc_selrefs
   segname __DATA
      addr 0x00000000000117a8
      size 0x00000000000000a8
    offset 71592
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x10000005
 reserved1 0
 reserved2 0
Section
  sectname __objc_classrefs
   segname __DATA
      addr 0x0000000000011850
      size 0x0000000000000038
    offset 71760
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x10000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000000011888
      size 0x0000000000000160
    offset 71816
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x00000000000119f0
      size 0x0000000000000200
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000000012000
   vmsize 0x000000000001c000
  fileoff 73728
 filesize 114112
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 72
         name @rpath/CoreMLHelpers.framework/CoreMLHelpers (offset 24)
   time stamp 1 Thu Jan  1 04:00:01 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 73728
    rebase_size 32
       bind_off 73760
      bind_size 2152
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 75912
 lazy_bind_size 4600
     export_off 80512
    export_size 4360
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 85216
   nsyms 1564
  stroff 111380
 strsize 55856
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 1271
     iextdefsym 1271
     nextdefsym 106
      iundefsym 1377
      nundefsym 187
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 110240
  nindirectsyms 285
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid 32FAE98E-894A-30CB-88D8-A65E3643064B
Load command 8
      cmd LC_VERSION_MIN_IPHONEOS
  cmdsize 16
  version 10.0
      sdk 12.2
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/Foundation.framework/Foundation (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1570.15.0
compatibility version 300.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libobjc.A.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 228.0.0
compatibility version 1.0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1252.250.1
compatibility version 1.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/Accelerate.framework/Accelerate (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 4.0.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1570.15.0
compatibility version 150.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1251.12.0
compatibility version 64.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/CoreImage.framework/CoreImage (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 5.0.0
compatibility version 1.0.0
Load command 17
          cmd LC_LOAD_WEAK_DYLIB
      cmdsize 80
         name /System/Library/Frameworks/CoreML.framework/CoreML (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/CoreVideo.framework/CoreVideo (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1.5.0
compatibility version 1.2.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name /System/Library/Frameworks/UIKit.framework/UIKit (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 61000.0.0
compatibility version 1.0.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/VideoToolbox.framework/VideoToolbox (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 21
          cmd LC_LOAD_WEAK_DYLIB
      cmdsize 80
         name /System/Library/Frameworks/Vision.framework/Vision (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 2.0.70
compatibility version 1.0.0
Load command 22
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftAccelerate.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 23
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftCore.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 24
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftCoreAudio.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 25
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/libswiftCoreFoundation.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 26
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/libswiftCoreGraphics.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 27
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftCoreImage.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 28
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftCoreMedia.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 29
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftDarwin.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 30
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftDispatch.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 31
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftFoundation.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 32
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftMetal.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 33
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftObjectiveC.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 34
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftQuartzCore.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 35
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftUIKit.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 36
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftVision.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 37
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libswiftos.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 38
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libswiftsimd.dylib (offset 24)
   time stamp 2 Thu Jan  1 04:00:02 1970
      current version 1001.0.82
compatibility version 1.0.0
Load command 39
          cmd LC_RPATH
      cmdsize 32
         path /usr/lib/swift (offset 12)
Load command 40
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 41
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
Load command 42
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 84872
 datasize 344
Load command 43
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 85216
 datasize 0
Load command 44
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 167248
 datasize 20592

```

**Comment by kabiroberai** [comment]
And what about `make clean all messages=yes`?

**Comment by mevinDhun** [comment]
```
MacBook-Air:swifter karim$ make clean all messages=yes
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 6 "Cleaning"); set -o pipefail; (rm -rf "/Users/karim/Documents/workspace/swifter/.theos/obj")
==> Cleaning…
set -o pipefail; (rm "/Users/karim/Documents/workspace/swifter/.theos/build_session")
set -o pipefail; (touch "/Users/karim/Documents/workspace/swifter/.theos/build_session")
set -o pipefail; (rm -rf "/Users/karim/Documents/workspace/swifter/.theos/_")
> Making all for bundle com.karim.swifter…
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/com.karim.swifter.bundle")
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/com.karim.swifter.bundle")
set -o pipefail; (mkdir -p "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/com.karim.swifter.bundle")
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 5 "Copying resource directories into the bundle wrapper"); set -o pipefail; (for d in Resources; do \
		if [[ -d "$d" ]]; then \
			rsync -a "$d/" "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/com.karim.swifter.bundle/" --exclude "_MTN" --exclude ".git" --exclude ".svn" --exclude ".DS_Store" --exclude "._*"; \
		else \
			printf "\e[0;33m==> \e[1;33mWarning:\e[m %s\n" "Ignoring missing bundle resource directory $d." >&2; \
		fi; \
	done)
==> Copying resource directories into the bundle wrapper…
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-keep-going COLOR=1 \
		internal-bundle-compile \
		_THEOS_CURRENT_TYPE=bundle THEOS_CURRENT_INSTANCE=com.karim.swifter _THEOS_CURRENT_OPERATION=compile \
		THEOS_BUILD_DIR="." _THEOS_MAKE_PARALLEL=yes
==> Warning: No files to link - creating a bundle containing only resources
> Making all for tweak swifter…
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-keep-going COLOR=1 \
		internal-library-compile \
		_THEOS_CURRENT_TYPE=tweak THEOS_CURRENT_INSTANCE=swifter _THEOS_CURRENT_OPERATION=compile \
		THEOS_BUILD_DIR="." _THEOS_MAKE_PARALLEL=yes
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-print-directory --no-keep-going internal-tweak-compile _THEOS_CURRENT_TYPE="tweak" THEOS_CURRENT_INSTANCE="swifter" _THEOS_CURRENT_OPERATION="compile" THEOS_BUILD_DIR="." THEOS_CURRENT_ARCH="arm64"
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 2 "Compiling UIImage+Depth.swift (arm64)"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-object -emit-module -c -I/Users/karim/theos/include -I/Users/karim/theos/vendor/include -I/Users/karim/theos/include/_fallback -emit-dependencies-path "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/UIImage+Depth.swift.f67d8c53.Td" -color-diagnostics -DTHEOS_SWIFT -DTARGET_IPHONE  -module-name swifter -g -sdk "/Users/karim/theos/sdks/iPhoneOS11.2.sdk"    -DDEBUG -Onone -target arm64-apple-ios11.2 -emit-module-path /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/UIImage+Depth.swift.f67d8c53.swiftmodule -primary-file UIImage+Depth.swift  -o /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/UIImage+Depth.swift.f67d8c53.o)
==> Compiling UIImage+Depth.swift (arm64)…
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/generated-headers/)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 4 "Generating swifter-Swift.h (arm64)"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -color-diagnostics -DTHEOS_SWIFT -DTARGET_IPHONE  -module-name swifter -g -sdk "/Users/karim/theos/sdks/iPhoneOS11.2.sdk"    -DDEBUG -Onone -target arm64-apple-ios11.2 -parse-as-library /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/UIImage+Depth.swift.f67d8c53.swiftmodule -emit-objc-header-path /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/generated-headers/swifter-Swift.h -o /dev/null)
==> Generating swifter-Swift.h (arm64)…
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 1 "Preprocessing Tweak.x"); set -o pipefail; (/Users/karim/theos/bin/logos.pl -c warnings=error -c generator=MobileSubstrate    Tweak.x > /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/Tweak.x.m)
==> Preprocessing Tweak.x…
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 2 "Compiling Tweak.x (arm64)"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -x objective-c -c -I"/Users/karim/Documents/workspace/swifter" -I/Users/karim/theos/include -I/Users/karim/theos/vendor/include -I/Users/karim/theos/include/_fallback -include /Users/karim/theos/Prefix.pch -I/Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/generated-headers/ -MT /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/Tweak.x.f67d8c53.o -MMD -MP -MF "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/Tweak.x.f67d8c53.Td" -fcolor-diagnostics -DTARGET_IPHONE=1 -O0 -Wall -ggdb -Werror  -isysroot "/Users/karim/theos/sdks/iPhoneOS11.2.sdk" -miphoneos-version-min=11.2 -fmodules -fcxx-modules -fmodule-name=swifter -fbuild-session-file=/Users/karim/Documents/workspace/swifter/.theos/build_session -fmodules-prune-after=345600 -fmodules-prune-interval=86400 -fmodules-validate-once-per-build-session   -fobjc-arc -DDEBUG -O0  -DTHEOS_INSTANCE_NAME="\"swifter\"" -fmodules -fcxx-modules -fmodule-name=swifter -fbuild-session-file=/Users/karim/Documents/workspace/swifter/.theos/build_session -fmodules-prune-after=345600 -fmodules-prune-interval=86400 -fmodules-validate-once-per-build-session  -arch arm64      -std=c99 /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/Tweak.x.m -o /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/Tweak.x.f67d8c53.o)
==> Compiling Tweak.x (arm64)…
set -o pipefail; (mkdir -p /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 3 "Linking tweak swifter (arm64)"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fcolor-diagnostics -L/Users/karim/theos/lib -ggdb -L/Users/karim/theos/vendor/lib -lobjc -framework Foundation -framework CoreFoundation -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/swift/iphoneos -rpath /usr/lib/libswift/stable  -framework CoreML -framework CoreGraphics -framework ImageIO -framework Accelerate -framework ARKit -framework CoreImage            -F/Users/karim/theos/vendor/lib -framework CydiaSubstrate -dynamiclib -install_name "/Library/MobileSubstrate/DynamicLibraries/swifter.dylib"  -isysroot "/Users/karim/theos/sdks/iPhoneOS11.2.sdk" -miphoneos-version-min=11.2  -multiply_defined suppress  -arch arm64 -F./ -O0 -o "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/swifter.dylib" /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/Tweak.x.f67d8c53.o /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/UIImage+Depth.swift.f67d8c53.o)
==> Linking tweak swifter (arm64)…
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 4 "Generating debug symbols for swifter"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/swifter.dylib")
==> Generating debug symbols for swifter…
rm /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/Tweak.x.m
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 4 "Merging tweak swifter"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -arch arm64 /Users/karim/Documents/workspace/swifter/.theos/obj/debug/arm64/swifter.dylib -create -output "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/swifter.dylib.47ba6b93.unsigned")
==> Merging tweak swifter…
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 4 "Signing swifter"); set -o pipefail; (CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate  ldid -S "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/swifter.dylib.47ba6b93.unsigned" && mv "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/swifter.dylib.47ba6b93.unsigned" "/Users/karim/Documents/workspace/swifter/.theos/obj/debug/swifter.dylib")
==> Signing swifter…
MacBook-Air:swifter karim$ 

```

**Comment by kabiroberai** [comment]
Seems like CoreMLHelpers doesn’t inherit the rpaths supplied by the swifter executable. Was CoreMLHelpers itself built using Theos? If not, you might need to add the rpath manually using `install_name_tool -add_rpath /usr/lib/libswift/stable <path to CoreMLTools>`. If it was built with Theos, could you give me the output of `make clean all messages=yes` for it?

**Comment by mevinDhun** [comment]
No this framework is one of the dependencies of a much bigger set of frameworks which was developed for ios apps. I am not not sure if adding the rpath manually to the frameworks i'll be using (around 8 frameworks) is the right way, so i'll stick to the symlink work-around in the meantime.

**Comment by kabiroberai** [comment]
I’d highly recommend the rpath method for now (you can do it automatically in your Makefile). I’ll add a symlink from /usr/lib/swift to /usr/lib/libswift/stable to the libswift package soon.

**Comment by kabiroberai** [comment]
For example
```
before-package::
    for dir in .theos/_/Libraries/MobileSubstrate/DynamicLibraries/com.karim.swifter.bundle/Frameworks/*; do \
        install_name_tool -add_rpath /usr/lib/libswift/stable $${dir}/$$(basename $${dir%.*}); \
done
```
(Note that this hasn’t been tested so you might need to modify it a little.)

**Comment by mevinDhun** [comment]
I tried it and the frameworks were loaded successfully. Thanks!

**Comment by liuxuan30** [comment]
@mevinDhun  sorry to dig this up.

I met similar issue like I said in https://github.com/theos/theos/issues/432,

when I link the framework like your makefile, the test tweak is not loaded at all. But my code is pure OBJC, so no swift involved. Have you figured out why the tweak is not loaded when 3rd party framework is linked?
