### ISSUE TITLE
arm64e compiliation on Linux

### ISSUE THREAD

**Issue by cbyrne** [theos/theos#482]
Is there any updates for arm64e compiling on Linux?
The error: ```clang: error: invalid arch name '-arch arm64e'``` occurs when trying to compile, using an iOS 12.2 sdk. Guessing the toolchain needs to be updated, is this planned?

**Edit:**
After trying @sbingner's suggestion:
> You could try the toolchain I have at https://github.com/sbingner/llvm-project/releases/tag/v10.0.0-1

I now get the error: ``ld: unknown/unsupported architecture name for: -arch arm64e``. Then when using an iOS 12.4 sdk it can't build any modules i.e. ``CoreFoundation``, ``Foundation`` and ``Darwin``. Full log of this issue available here: https://psty.io/p?q=1ea6a

**Comment by sbingner** [comment]
You could try the toolchain I have at https://github.com/sbingner/llvm-project/releases/tag/v10.0.0-1

**Comment by ConorTheDev** [comment]
Will have a look at it

**Comment by ConorTheDev** [comment]
Added ```~/ios-arm64e-clang-toolchain/bin/`` to my PATH variable. Getting a different error this time but no further compilation, does it need a newer SDK? Currently using 11.2, fyi.
![image](https://user-images.githubusercontent.com/31479541/74571897-33157180-4f76-11ea-9093-bd3724f4deff.png)

**Comment by ConorTheDev** [comment]
Note: when using an iOS 12.4 patched SDK, I'm getting a massive console log of errors like this, theos on linux does need some work! :stuck_out_tongue: 
![image](https://user-images.githubusercontent.com/31479541/74572180-9ef7da00-4f76-11ea-90af-e69f3cbc19dd.png)

**Comment by sbingner** [comment]
you probably need to use wrapper scripts to execute clang with -target etc properly

**Comment by uroboro** [comment]
Fixed with 8771215f765e774bfefdacc6ddf0e151c2973d49

**Comment by LaxusiC** [comment]
@sbingner I'm new to making tweak, how do I install the toolchain correctly? I extract and put in /usr/ but still can't compile for arm64e. Am I doing wrong?
