### ISSUE TITLE
Environment variable not taking effect

### ISSUE THREAD

**Issue by prolitornandbasturtrumerthydempe** [theos/theos#534]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. ` brew install ldid xz`
2. `echo "export THEOS=~/theos" >> ~/.profile`
3. `echo $THEOS`

What happens?
-------------
No path output

What were you expecting to happen?
----------------------------------
Theos path output

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
No path output. Blank line.

Any other comments?
-------------------
`echo $SHELL`
`/bin/bash`

`cat .profile`
```
# MacPorts Installer addition on 2020-06-26_at_13:14:57: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

export THEOS=~/theos
```

What versions of software are you using?
----------------------------------------
**Operating System:** Mac OS Mojave

**Toolchain Version:** N/A

**SDK Version:** N/A

**Comment by prolitornandbasturtrumerthydempe** [comment]
FIXED:
**You must close the terminal and reopen. Closing the tab and opening a new tab is not sufficient.**

**Comment by kirb** [comment]
You missed a step. Profile scripts are executed when the shell starts up. Nothing will happen by just writing things to them - you need to start a new shell session (e.g. open a new tab).

If you didn’t use the official [instructions](https://git.io/theosinstall), I’d suggest you start over with that. If you’re on macOS Catalina then be aware that the default shell is now zsh, which does not use `~/.profile`. That’s covered in our instructions.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
